services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.dev
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.dev
    ports:
      - "5000:5000"
